<?php
/**
 * The plugin's own shipped file checksums.
 *
 * @package LightweightPlugins\Scan
 */

declare(strict_types=1);

namespace LightweightPlugins\Scan\Index;

use function LightweightPlugins\Scan\lw_scan_relative_path;

defined( 'ABSPATH' ) || exit;

/**
 * Reads `checksums.json` from the plugin root: the manifest generated by
 * `composer checksums` and shipped in the release ZIP. The scanner's own
 * decoder and heuristic sources necessarily contain the very strings the
 * signatures look for, so without this list lw-scan reports itself as
 * infected on every install. A file whose md5 is not exactly the shipped
 * one is deliberately NOT known-good: a tampered copy of the plugin must
 * still be scanned.
 */
final class SelfManifest {

	/** Manifest file name, at the plugin root. */
	public const FILE = 'checksums.json';

	/**
	 * Absolute plugin directory with a trailing slash, or '' when unknown.
	 *
	 * @var string
	 */
	private string $dir;

	/**
	 * Plugin-relative path => md5, loaded on first use.
	 *
	 * @var array<string,string>
	 */
	private array $files = [];

	/**
	 * @var string
	 */
	private string $version = '';

	/**
	 * @var bool
	 */
	private bool $loaded = false;

	/**
	 * @param string $plugin_dir Absolute plugin directory; defaults to LW_SCAN_PATH.
	 */
	public function __construct( string $plugin_dir = '' ) {
		if ( '' === $plugin_dir && defined( 'LW_SCAN_PATH' ) ) {
			$plugin_dir = (string) LW_SCAN_PATH;
		}

		$plugin_dir = str_replace( '\\', '/', $plugin_dir );
		$this->dir  = '' === $plugin_dir ? '' : rtrim( $plugin_dir, '/' ) . '/';
	}

	/**
	 * The plugin's own directory relative to ABSPATH, with a trailing slash
	 * ('' when the plugin path is unknown). Callers compare a scanned file's
	 * relative path against this prefix.
	 *
	 * @return string
	 */
	public function root(): string {
		if ( '' === $this->dir ) {
			return '';
		}

		return rtrim( lw_scan_relative_path( $this->dir ), '/' ) . '/';
	}

	/**
	 * @param string $rel_inside_plugin Path relative to the plugin directory, e.g. `includes/Plugin.php`.
	 * @return string|null Shipped md5, or null when the file is not in the manifest.
	 */
	public function md5_for( string $rel_inside_plugin ): ?string {
		$this->load();

		return $this->files[ $rel_inside_plugin ] ?? null;
	}

	/**
	 * Plugin version the manifest was generated for ('' when unavailable).
	 *
	 * @return string
	 */
	public function version(): string {
		$this->load();

		return $this->version;
	}

	/**
	 * @return void
	 */
	private function load(): void {
		if ( $this->loaded ) {
			return;
		}

		$this->loaded = true;

		$file = $this->dir . self::FILE;

		if ( '' === $this->dir || ! is_readable( $file ) ) {
			return;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- the plugin's own manifest, shipped next to this file; not a remote URL.
		$contents = file_get_contents( $file );
		$decoded  = false === $contents ? null : json_decode( $contents, true );

		if ( ! is_array( $decoded ) ) {
			return;
		}

		$this->version = is_string( $decoded['version'] ?? null ) ? $decoded['version'] : '';
		$files         = is_array( $decoded['files'] ?? null ) ? $decoded['files'] : [];

		foreach ( $files as $path => $md5 ) {
			if ( is_string( $md5 ) && '' !== $md5 ) {
				$this->files[ (string) $path ] = $md5;
			}
		}
	}
}
